name       : quodlibet
version    : 3.9.0
release    : 5
source     :
    - https://github.com/quodlibet/quodlibet/archive/release-3.9.0.tar.gz : 974de36040f75d067748825e308e095fdd1d95bd443ba10cc0779e5f7589da39
license    : GPL-2.0
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
builddeps  :
    - intltool
rundeps    :
    - keybinder
    - libwebkit-gtk
    - media-player-info
    - mutagen
    - python-cairo
    - python-dbus
    - python-faulthandler
    - python-feedparser
    - python-futures
    - python-gobject
    - python-inotify
    - python-musicbrainzngs
    - rygel
build      : |
    cd quodlibet
    %python_setup
install    : |
    cd quodlibet
    %python_install
