name       : quodlibet
version    : 4.2.1
release    : 15
source     :
    - https://github.com/quodlibet/quodlibet/archive/release-4.2.1.tar.gz : 77d0c0a623d36f97e79167d3c9fc63f024cb60e120aecddbaf9ff129bc1a6533
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
rundeps    :
    - gstreamer-1.0-plugins-good
    - keybinder
    - libwebkit-gtk
    - mutagen
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python-feedparser
    - python-inotify
    - python-musicbrainzngs
    - rygel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-zsh-completion-path.patch
build      : |
    pushd quodlibet
    python3 setup.py build
    popd
install    : |
    pushd quodlibet
    python3 setup.py install --root="%installroot%"
    popd
