name       : quodlibet
version    : 4.3.0
release    : 20
source     :
    - https://github.com/quodlibet/quodlibet/releases/download/release-4.3.0/quodlibet-4.3.0.tar.gz : a2e5c027a69f138364c57e4adf72f5c08c235bc09a4bcd8f668e2847d76427e0
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
rundeps    :
    - gstreamer-1.0-plugins-good
    - keybinder
    - libwebkit-gtk
    - mutagen
    - python3-cairo
    - python3-dbus
    - python-feedparser
    - python-gobject
    - python-inotify
    - python-musicbrainzngs
    - rygel
build      : |
    %python3_setup
install    : |
    %python3_install
