name       : quodlibet
version    : 4.2.0
release    : 14
source     :
    - https://github.com/quodlibet/quodlibet/releases/download/release-4.2.0/quodlibet-4.2.0.tar.gz : c68d5c8aa7ffae514f878a1b52a769558974ae3cfc53c2c892efdf98528ac470
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
rundeps    :
    - gstreamer-1.0-plugins-good
    - keybinder
    - libwebkit-gtk
    - mutagen
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - python-feedparser
    - python-inotify
    - python-musicbrainzngs
    - rygel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-zsh-completion-path.patch
build      : |
    %python3_setup
install    : |
    %python3_install
