name       : quodlibet
version    : 4.5.0
release    : 24
source     :
    - https://github.com/quodlibet/quodlibet/releases/download/release-4.5.0/quodlibet-4.5.0.tar.gz : 301615829f652cbafedb35539237162a58bc1ee71a567d249f7789d9268245bc
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different ways to view your audio library, as well as support for Internet radio and audio feeds. It has extremely flexible metadata tag editing and searching capabilities. Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
rundeps    :
    - gstreamer-1.0-plugins-good
    - keybinder
    - libwebkit-gtk
    - mutagen
    - python-feedparser
    - python-gobject
    - python-inotify
    - python-musicbrainzngs
    - python3-dbus
    - rygel
build      : |
    %python3_setup
install    : |
    %python3_install
