name       : quodlibet
version    : 4.0.2
release    : 11
source     :
    - https://github.com/quodlibet/quodlibet/releases/download/release-4.0.2/quodlibet-4.0.2.tar.gz : df156eaee6779a98f543c450f7bf44fae55dbcee6ddd0310f504d971074a5a1c
license    : GPL-2.0
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
builddeps  :
    - intltool
rundeps    :
    - keybinder
    - libwebkit-gtk
    - mutagen
    - python-feedparser
    - python-inotify
    - python-musicbrainzngs
    - python3-cairo
    - python3-dbus
    - python3-gobject
    - rygel
build      : |
    %python3_setup
install    : |
    %python3_install
