name       : quodlibet
version    : 3.8.1
release    : 4
source     :
    - https://github.com/quodlibet/quodlibet/archive/release-3.8.1.tar.gz : 7c26ddd391a7b3d2bcdb4b009b005db604a133a059499284613436a88d164401
license    : GPL-2.0
component  : multimedia.audio
summary    : A music library, tagger and player
description: |
    Quod Libet is a music management program. It provides several different
    ways to view your audio library, as well as support for Internet radio and
    audio feeds. It has extremely flexible metadata tag editing and searching
    capabilities.
    Ex Falso is a tag editor with the same tag editing interface as Quod Libet.
builddeps  :
    - gettext
    - intltool
rundeps    :
    - keybinder
    - libwebkit-gtk
    - mutagen
    - notify-python
    - python-cairo
    - python-dbus
    - python-feedparser
    - python-futures
    - python-gobject
    - python-musicbrainzngs
build      : |
    cd quodlibet
    %python_setup
install    : |
    cd quodlibet
    %python_install
